//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.ufg.inf.esp.ria.modelo.preferencias;

import android.content.Context;
import android.content.SharedPreferences;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class ELogado_
    extends SharedPreferencesHelper
{


    public ELogado_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_ELogado"), 0));
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public ELogado_.ELogadoEditor_ edit() {
        return new ELogado_.ELogadoEditor_(getSharedPreferences());
    }

    public StringPrefField identificacao() {
        return stringField("identificacao", "");
    }

    public final static class ELogadoEditor_
        extends EditorHelper<ELogado_.ELogadoEditor_>
    {


        ELogadoEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<ELogado_.ELogadoEditor_> identificacao() {
            return stringField("identificacao");
        }

    }

}
