//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.ufg.inf.esp.ria.login.loginpersistente;

import android.app.Activity;
import android.content.Context;
import android.widget.TextView;
import br.ufg.inf.esp.ria.login.loginpersistente.R.id;
import br.ufg.inf.esp.ria.login.loginpersistente.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ItemSiteView_
    extends ItemSiteView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public ItemSiteView_(Context context) {
        super(context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        nome = ((TextView) findViewById(id.nome));
        descricao = ((TextView) findViewById(id.descricao));
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.lista_site, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static ItemSiteView build(Context context) {
        ItemSiteView_ instance = new ItemSiteView_(context);
        instance.onFinishInflate();
        return instance;
    }

}
