//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.ufg.inf.esp.ria.login.loginpersistente;

import android.app.Activity;
import android.content.Context;
import android.view.View;

public final class ListaSiteAdapter_
    extends ListaSiteAdapter
{

    private Context context_;

    private ListaSiteAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        contexto = context_;
        initAdapter();
    }

    public static ListaSiteAdapter_ getInstance_(Context context) {
        return new ListaSiteAdapter_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
